services: # Serviços que esse compose terá
  postgres: # Configurações do postgres
    image: postgres # Imagem usada
    container_name: postgres_credit_analysis # Nome do container
    environment: # Variávies de ambiente
      POSTGRES_USER: admin # Usuário para se conectar
      POSTGRES_PASSWORD: root # Senha para se conectar
    ports: # portas (porta de conexão do compose : porta de conexão do serviço dentro do container )
      - "5433:5432"

  adminer:
    image: adminer
    container_name: adminer_credit_analysis
    restart: always
    ports: # portas  (porta de conexão do compose: porta de conexão do serviço dentro do container )
      - "9002:8080"
